apiVersion: apps/v1
kind: Deployment
metadata: 
  name: front
  labels: 
    name: front
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: front
  template:
    metadata:
      labels:
        name: front
    spec:
      containers:
      - image: 312496994610.dkr.ecr.us-east-1.amazonaws.com/fred-wize:e280388
        name: front  
        ports:
        - containerPort: 8080
          name: http 
          protocol: TCP
        livenessProbe: 
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
        readinessProbe:
          httpGet: 
            path: /health
            port: 8080
          initialDelaySeconds: 1

        env:
        - name: NEXT_URL
          value: "http://middle/api"
        resources: {}  
---
kind: Service
apiVersion: v1
metadata:
  name: front
spec:
  selector:
    name: front
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    targetPort: http


