apiVersion: apps/v1
kind: Deployment
metadata: 
  name: back
  labels: 
    name: back
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: back
  template:
    metadata:
      labels:
        name: back
    spec:
      containers:
      - image: 312496994610.dkr.ecr.us-east-1.amazonaws.com/fred-wize-go
        name: back  
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe: 
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
        resources: {}  
---
kind: Service
apiVersion: v1
metadata:
  name: back
spec:
  selector:
    name: back
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 8080
