apiVersion: apps/v1
kind: Deployment
metadata: 
  name: middle
  labels: 
    name: middle
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: middle
  template:
    metadata:
      labels:
        name: middle
    spec:
      containers:
      - image: 312496994610.dkr.ecr.us-east-1.amazonaws.com/fred-wize-nodejs:71a96ed
        name: middle  
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe: 
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
        env:
        - name: NEXT_URL
          value: "http://back/api"
        resources: {}  
---
kind: Service
apiVersion: v1
metadata:
  name: middle
spec:
  selector:
    name: middle
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 8080
